name: Dependabot auto-merge

on:
  pull_request:
    types: [ opened ]

jobs:

  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:

      - name: 'Comment merge command'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '@dependabot merge'
            })
