name: Publish

on:
  push:
    tags:
      - '*'

jobs:

  publish:
    name: publish
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run build

      - name: Create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - if: contains(github.ref, '-beta')
        run: npm publish --access public --tag beta

      - if: "!contains(github.ref, '-beta')"
        run: npm publish --access public

