name: CI

on:  
  push:
    branches: 
      - master
  pull_request:
  schedule:
    - cron: "0 9 * * *"

jobs:

  lint:
    name: Lint code
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - run: npm run lint

  test-ubuntu:
    name: Ubuntu test
    needs: lint
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - run: xvfb-run --server-args="-screen 0 1024x768x24" npm run test:coverage
      - uses: codecov/codecov-action@v1
        
  test-macos:
    name: macOS test
    needs: lint
    runs-on: [macOS-latest]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - run: npm run test

  test-windows:
    name: Windows test
    needs: lint
    runs-on: [windows-latest]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - run: npm run test
