name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  lint:
    name: Lint code
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run lint

  test-ubuntu:
    name: Ubuntu test
    needs: lint
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: xvfb-run --server-args="-screen 0 1024x768x24" npm run test:coverage
      - uses: codecov/codecov-action@v1

  test-macos:
    name: macOS test
    needs: lint
    runs-on: [macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run test

  test-windows:
    name: Windows test
    needs: lint
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run test
